"""Repository interface for IMC dashboard persistence."""

from __future__ import annotations

from typing import Protocol

from domain.entities import ParsedReport


class ReportRepository(Protocol):
    def get_health_status(self) -> dict: ...

    def save_report(self, path: str, report: ParsedReport) -> None: ...

    def list_report_dates(self) -> list[str]: ...

    def list_report_date_metadata(self) -> list[dict]: ...

    def list_reports(self) -> list[dict]: ...

    def delete_report(self, report_date: str, *, delete_file: bool = True) -> dict: ...

    def get_report_file_path(self, report_date: str) -> str | None: ...

    def get_validation_logs(self, report_date: str) -> list[dict]: ...

    def get_system_status(self) -> dict: ...

    def list_threshold_configs(self) -> list[dict]: ...

    def update_threshold_config(self, metric_name: str, payload: dict) -> None: ...

    def list_operation_periods(self) -> list[dict]: ...

    def create_operation_period(self, payload: dict) -> dict: ...

    def update_operation_period(self, period_id: int, payload: dict) -> dict: ...

    def delete_operation_period(self, period_id: int) -> bool: ...

    def get_dashboard_summary(self, report_date: str, compare_basis: str = "prev_day") -> dict: ...

    def get_volume_analysis(self, report_date: str) -> dict: ...

    def get_staffing_analysis(self, report_date: str) -> dict: ...

    def get_transport_analysis(self, report_date: str) -> dict: ...

    def get_equipment_analysis(self, report_date: str) -> dict: ...

    def get_safety_analysis(self, report_date: str) -> dict: ...

    def get_briefing_data(self, report_date: str) -> dict: ...
